
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrderReferenceCounter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OrderReferenceCounter
 * 
 */
export type OrderReferenceCounterModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderReferenceCounterPayload>

export type AggregateOrderReferenceCounter = {
  _count: OrderReferenceCounterCountAggregateOutputType | null
  _avg: OrderReferenceCounterAvgAggregateOutputType | null
  _sum: OrderReferenceCounterSumAggregateOutputType | null
  _min: OrderReferenceCounterMinAggregateOutputType | null
  _max: OrderReferenceCounterMaxAggregateOutputType | null
}

export type OrderReferenceCounterAvgAggregateOutputType = {
  nextValue: number | null
}

export type OrderReferenceCounterSumAggregateOutputType = {
  nextValue: number | null
}

export type OrderReferenceCounterMinAggregateOutputType = {
  id: string | null
  nextValue: number | null
}

export type OrderReferenceCounterMaxAggregateOutputType = {
  id: string | null
  nextValue: number | null
}

export type OrderReferenceCounterCountAggregateOutputType = {
  id: number
  nextValue: number
  _all: number
}


export type OrderReferenceCounterAvgAggregateInputType = {
  nextValue?: true
}

export type OrderReferenceCounterSumAggregateInputType = {
  nextValue?: true
}

export type OrderReferenceCounterMinAggregateInputType = {
  id?: true
  nextValue?: true
}

export type OrderReferenceCounterMaxAggregateInputType = {
  id?: true
  nextValue?: true
}

export type OrderReferenceCounterCountAggregateInputType = {
  id?: true
  nextValue?: true
  _all?: true
}

export type OrderReferenceCounterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderReferenceCounter to aggregate.
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderReferenceCounters to fetch.
   */
  orderBy?: Prisma.OrderReferenceCounterOrderByWithRelationInput | Prisma.OrderReferenceCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderReferenceCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderReferenceCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderReferenceCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrderReferenceCounters
  **/
  _count?: true | OrderReferenceCounterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderReferenceCounterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderReferenceCounterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderReferenceCounterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderReferenceCounterMaxAggregateInputType
}

export type GetOrderReferenceCounterAggregateType<T extends OrderReferenceCounterAggregateArgs> = {
      [P in keyof T & keyof AggregateOrderReferenceCounter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrderReferenceCounter[P]>
    : Prisma.GetScalarType<T[P], AggregateOrderReferenceCounter[P]>
}




export type OrderReferenceCounterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderReferenceCounterWhereInput
  orderBy?: Prisma.OrderReferenceCounterOrderByWithAggregationInput | Prisma.OrderReferenceCounterOrderByWithAggregationInput[]
  by: Prisma.OrderReferenceCounterScalarFieldEnum[] | Prisma.OrderReferenceCounterScalarFieldEnum
  having?: Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderReferenceCounterCountAggregateInputType | true
  _avg?: OrderReferenceCounterAvgAggregateInputType
  _sum?: OrderReferenceCounterSumAggregateInputType
  _min?: OrderReferenceCounterMinAggregateInputType
  _max?: OrderReferenceCounterMaxAggregateInputType
}

export type OrderReferenceCounterGroupByOutputType = {
  id: string
  nextValue: number
  _count: OrderReferenceCounterCountAggregateOutputType | null
  _avg: OrderReferenceCounterAvgAggregateOutputType | null
  _sum: OrderReferenceCounterSumAggregateOutputType | null
  _min: OrderReferenceCounterMinAggregateOutputType | null
  _max: OrderReferenceCounterMaxAggregateOutputType | null
}

type GetOrderReferenceCounterGroupByPayload<T extends OrderReferenceCounterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderReferenceCounterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderReferenceCounterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderReferenceCounterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderReferenceCounterGroupByOutputType[P]>
      }
    >
  >



export type OrderReferenceCounterWhereInput = {
  AND?: Prisma.OrderReferenceCounterWhereInput | Prisma.OrderReferenceCounterWhereInput[]
  OR?: Prisma.OrderReferenceCounterWhereInput[]
  NOT?: Prisma.OrderReferenceCounterWhereInput | Prisma.OrderReferenceCounterWhereInput[]
  id?: Prisma.StringFilter<"OrderReferenceCounter"> | string
  nextValue?: Prisma.IntFilter<"OrderReferenceCounter"> | number
}

export type OrderReferenceCounterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nextValue?: Prisma.SortOrder
}

export type OrderReferenceCounterWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OrderReferenceCounterWhereInput | Prisma.OrderReferenceCounterWhereInput[]
  OR?: Prisma.OrderReferenceCounterWhereInput[]
  NOT?: Prisma.OrderReferenceCounterWhereInput | Prisma.OrderReferenceCounterWhereInput[]
  nextValue?: Prisma.IntFilter<"OrderReferenceCounter"> | number
}, "id">

export type OrderReferenceCounterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nextValue?: Prisma.SortOrder
  _count?: Prisma.OrderReferenceCounterCountOrderByAggregateInput
  _avg?: Prisma.OrderReferenceCounterAvgOrderByAggregateInput
  _max?: Prisma.OrderReferenceCounterMaxOrderByAggregateInput
  _min?: Prisma.OrderReferenceCounterMinOrderByAggregateInput
  _sum?: Prisma.OrderReferenceCounterSumOrderByAggregateInput
}

export type OrderReferenceCounterScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput | Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput | Prisma.OrderReferenceCounterScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrderReferenceCounter"> | string
  nextValue?: Prisma.IntWithAggregatesFilter<"OrderReferenceCounter"> | number
}

export type OrderReferenceCounterCreateInput = {
  id?: string
  nextValue?: number
}

export type OrderReferenceCounterUncheckedCreateInput = {
  id?: string
  nextValue?: number
}

export type OrderReferenceCounterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nextValue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrderReferenceCounterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nextValue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrderReferenceCounterCreateManyInput = {
  id?: string
  nextValue?: number
}

export type OrderReferenceCounterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nextValue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrderReferenceCounterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nextValue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrderReferenceCounterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nextValue?: Prisma.SortOrder
}

export type OrderReferenceCounterAvgOrderByAggregateInput = {
  nextValue?: Prisma.SortOrder
}

export type OrderReferenceCounterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nextValue?: Prisma.SortOrder
}

export type OrderReferenceCounterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nextValue?: Prisma.SortOrder
}

export type OrderReferenceCounterSumOrderByAggregateInput = {
  nextValue?: Prisma.SortOrder
}



export type OrderReferenceCounterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nextValue?: boolean
}, ExtArgs["result"]["orderReferenceCounter"]>

export type OrderReferenceCounterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nextValue?: boolean
}, ExtArgs["result"]["orderReferenceCounter"]>

export type OrderReferenceCounterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nextValue?: boolean
}, ExtArgs["result"]["orderReferenceCounter"]>

export type OrderReferenceCounterSelectScalar = {
  id?: boolean
  nextValue?: boolean
}

export type OrderReferenceCounterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nextValue", ExtArgs["result"]["orderReferenceCounter"]>

export type $OrderReferenceCounterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrderReferenceCounter"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nextValue: number
  }, ExtArgs["result"]["orderReferenceCounter"]>
  composites: {}
}

export type OrderReferenceCounterGetPayload<S extends boolean | null | undefined | OrderReferenceCounterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload, S>

export type OrderReferenceCounterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderReferenceCounterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderReferenceCounterCountAggregateInputType | true
  }

export interface OrderReferenceCounterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrderReferenceCounter'], meta: { name: 'OrderReferenceCounter' } }
  /**
   * Find zero or one OrderReferenceCounter that matches the filter.
   * @param {OrderReferenceCounterFindUniqueArgs} args - Arguments to find a OrderReferenceCounter
   * @example
   * // Get one OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderReferenceCounterFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrderReferenceCounter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderReferenceCounterFindUniqueOrThrowArgs} args - Arguments to find a OrderReferenceCounter
   * @example
   * // Get one OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderReferenceCounterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderReferenceCounter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterFindFirstArgs} args - Arguments to find a OrderReferenceCounter
   * @example
   * // Get one OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderReferenceCounterFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderReferenceCounter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterFindFirstOrThrowArgs} args - Arguments to find a OrderReferenceCounter
   * @example
   * // Get one OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderReferenceCounterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrderReferenceCounters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrderReferenceCounters
   * const orderReferenceCounters = await prisma.orderReferenceCounter.findMany()
   * 
   * // Get first 10 OrderReferenceCounters
   * const orderReferenceCounters = await prisma.orderReferenceCounter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderReferenceCounterWithIdOnly = await prisma.orderReferenceCounter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderReferenceCounterFindManyArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrderReferenceCounter.
   * @param {OrderReferenceCounterCreateArgs} args - Arguments to create a OrderReferenceCounter.
   * @example
   * // Create one OrderReferenceCounter
   * const OrderReferenceCounter = await prisma.orderReferenceCounter.create({
   *   data: {
   *     // ... data to create a OrderReferenceCounter
   *   }
   * })
   * 
   */
  create<T extends OrderReferenceCounterCreateArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterCreateArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrderReferenceCounters.
   * @param {OrderReferenceCounterCreateManyArgs} args - Arguments to create many OrderReferenceCounters.
   * @example
   * // Create many OrderReferenceCounters
   * const orderReferenceCounter = await prisma.orderReferenceCounter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderReferenceCounterCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrderReferenceCounters and returns the data saved in the database.
   * @param {OrderReferenceCounterCreateManyAndReturnArgs} args - Arguments to create many OrderReferenceCounters.
   * @example
   * // Create many OrderReferenceCounters
   * const orderReferenceCounter = await prisma.orderReferenceCounter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrderReferenceCounters and only return the `id`
   * const orderReferenceCounterWithIdOnly = await prisma.orderReferenceCounter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrderReferenceCounterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrderReferenceCounter.
   * @param {OrderReferenceCounterDeleteArgs} args - Arguments to delete one OrderReferenceCounter.
   * @example
   * // Delete one OrderReferenceCounter
   * const OrderReferenceCounter = await prisma.orderReferenceCounter.delete({
   *   where: {
   *     // ... filter to delete one OrderReferenceCounter
   *   }
   * })
   * 
   */
  delete<T extends OrderReferenceCounterDeleteArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrderReferenceCounter.
   * @param {OrderReferenceCounterUpdateArgs} args - Arguments to update one OrderReferenceCounter.
   * @example
   * // Update one OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderReferenceCounterUpdateArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrderReferenceCounters.
   * @param {OrderReferenceCounterDeleteManyArgs} args - Arguments to filter OrderReferenceCounters to delete.
   * @example
   * // Delete a few OrderReferenceCounters
   * const { count } = await prisma.orderReferenceCounter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderReferenceCounterDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderReferenceCounterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderReferenceCounters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrderReferenceCounters
   * const orderReferenceCounter = await prisma.orderReferenceCounter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderReferenceCounterUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderReferenceCounters and returns the data updated in the database.
   * @param {OrderReferenceCounterUpdateManyAndReturnArgs} args - Arguments to update many OrderReferenceCounters.
   * @example
   * // Update many OrderReferenceCounters
   * const orderReferenceCounter = await prisma.orderReferenceCounter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrderReferenceCounters and only return the `id`
   * const orderReferenceCounterWithIdOnly = await prisma.orderReferenceCounter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrderReferenceCounterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrderReferenceCounter.
   * @param {OrderReferenceCounterUpsertArgs} args - Arguments to update or create a OrderReferenceCounter.
   * @example
   * // Update or create a OrderReferenceCounter
   * const orderReferenceCounter = await prisma.orderReferenceCounter.upsert({
   *   create: {
   *     // ... data to create a OrderReferenceCounter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrderReferenceCounter we want to update
   *   }
   * })
   */
  upsert<T extends OrderReferenceCounterUpsertArgs>(args: Prisma.SelectSubset<T, OrderReferenceCounterUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderReferenceCounterClient<runtime.Types.Result.GetResult<Prisma.$OrderReferenceCounterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrderReferenceCounters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterCountArgs} args - Arguments to filter OrderReferenceCounters to count.
   * @example
   * // Count the number of OrderReferenceCounters
   * const count = await prisma.orderReferenceCounter.count({
   *   where: {
   *     // ... the filter for the OrderReferenceCounters we want to count
   *   }
   * })
  **/
  count<T extends OrderReferenceCounterCountArgs>(
    args?: Prisma.Subset<T, OrderReferenceCounterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderReferenceCounterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrderReferenceCounter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderReferenceCounterAggregateArgs>(args: Prisma.Subset<T, OrderReferenceCounterAggregateArgs>): Prisma.PrismaPromise<GetOrderReferenceCounterAggregateType<T>>

  /**
   * Group by OrderReferenceCounter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderReferenceCounterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderReferenceCounterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderReferenceCounterGroupByArgs['orderBy'] }
      : { orderBy?: OrderReferenceCounterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderReferenceCounterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderReferenceCounterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrderReferenceCounter model
 */
readonly fields: OrderReferenceCounterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrderReferenceCounter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderReferenceCounterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrderReferenceCounter model
 */
export interface OrderReferenceCounterFieldRefs {
  readonly id: Prisma.FieldRef<"OrderReferenceCounter", 'String'>
  readonly nextValue: Prisma.FieldRef<"OrderReferenceCounter", 'Int'>
}
    

// Custom InputTypes
/**
 * OrderReferenceCounter findUnique
 */
export type OrderReferenceCounterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter, which OrderReferenceCounter to fetch.
   */
  where: Prisma.OrderReferenceCounterWhereUniqueInput
}

/**
 * OrderReferenceCounter findUniqueOrThrow
 */
export type OrderReferenceCounterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter, which OrderReferenceCounter to fetch.
   */
  where: Prisma.OrderReferenceCounterWhereUniqueInput
}

/**
 * OrderReferenceCounter findFirst
 */
export type OrderReferenceCounterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter, which OrderReferenceCounter to fetch.
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderReferenceCounters to fetch.
   */
  orderBy?: Prisma.OrderReferenceCounterOrderByWithRelationInput | Prisma.OrderReferenceCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderReferenceCounters.
   */
  cursor?: Prisma.OrderReferenceCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderReferenceCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderReferenceCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderReferenceCounters.
   */
  distinct?: Prisma.OrderReferenceCounterScalarFieldEnum | Prisma.OrderReferenceCounterScalarFieldEnum[]
}

/**
 * OrderReferenceCounter findFirstOrThrow
 */
export type OrderReferenceCounterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter, which OrderReferenceCounter to fetch.
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderReferenceCounters to fetch.
   */
  orderBy?: Prisma.OrderReferenceCounterOrderByWithRelationInput | Prisma.OrderReferenceCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderReferenceCounters.
   */
  cursor?: Prisma.OrderReferenceCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderReferenceCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderReferenceCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderReferenceCounters.
   */
  distinct?: Prisma.OrderReferenceCounterScalarFieldEnum | Prisma.OrderReferenceCounterScalarFieldEnum[]
}

/**
 * OrderReferenceCounter findMany
 */
export type OrderReferenceCounterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter, which OrderReferenceCounters to fetch.
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderReferenceCounters to fetch.
   */
  orderBy?: Prisma.OrderReferenceCounterOrderByWithRelationInput | Prisma.OrderReferenceCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrderReferenceCounters.
   */
  cursor?: Prisma.OrderReferenceCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderReferenceCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderReferenceCounters.
   */
  skip?: number
  distinct?: Prisma.OrderReferenceCounterScalarFieldEnum | Prisma.OrderReferenceCounterScalarFieldEnum[]
}

/**
 * OrderReferenceCounter create
 */
export type OrderReferenceCounterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * The data needed to create a OrderReferenceCounter.
   */
  data?: Prisma.XOR<Prisma.OrderReferenceCounterCreateInput, Prisma.OrderReferenceCounterUncheckedCreateInput>
}

/**
 * OrderReferenceCounter createMany
 */
export type OrderReferenceCounterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrderReferenceCounters.
   */
  data: Prisma.OrderReferenceCounterCreateManyInput | Prisma.OrderReferenceCounterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderReferenceCounter createManyAndReturn
 */
export type OrderReferenceCounterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * The data used to create many OrderReferenceCounters.
   */
  data: Prisma.OrderReferenceCounterCreateManyInput | Prisma.OrderReferenceCounterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderReferenceCounter update
 */
export type OrderReferenceCounterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * The data needed to update a OrderReferenceCounter.
   */
  data: Prisma.XOR<Prisma.OrderReferenceCounterUpdateInput, Prisma.OrderReferenceCounterUncheckedUpdateInput>
  /**
   * Choose, which OrderReferenceCounter to update.
   */
  where: Prisma.OrderReferenceCounterWhereUniqueInput
}

/**
 * OrderReferenceCounter updateMany
 */
export type OrderReferenceCounterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrderReferenceCounters.
   */
  data: Prisma.XOR<Prisma.OrderReferenceCounterUpdateManyMutationInput, Prisma.OrderReferenceCounterUncheckedUpdateManyInput>
  /**
   * Filter which OrderReferenceCounters to update
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * Limit how many OrderReferenceCounters to update.
   */
  limit?: number
}

/**
 * OrderReferenceCounter updateManyAndReturn
 */
export type OrderReferenceCounterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * The data used to update OrderReferenceCounters.
   */
  data: Prisma.XOR<Prisma.OrderReferenceCounterUpdateManyMutationInput, Prisma.OrderReferenceCounterUncheckedUpdateManyInput>
  /**
   * Filter which OrderReferenceCounters to update
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * Limit how many OrderReferenceCounters to update.
   */
  limit?: number
}

/**
 * OrderReferenceCounter upsert
 */
export type OrderReferenceCounterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * The filter to search for the OrderReferenceCounter to update in case it exists.
   */
  where: Prisma.OrderReferenceCounterWhereUniqueInput
  /**
   * In case the OrderReferenceCounter found by the `where` argument doesn't exist, create a new OrderReferenceCounter with this data.
   */
  create: Prisma.XOR<Prisma.OrderReferenceCounterCreateInput, Prisma.OrderReferenceCounterUncheckedCreateInput>
  /**
   * In case the OrderReferenceCounter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderReferenceCounterUpdateInput, Prisma.OrderReferenceCounterUncheckedUpdateInput>
}

/**
 * OrderReferenceCounter delete
 */
export type OrderReferenceCounterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
  /**
   * Filter which OrderReferenceCounter to delete.
   */
  where: Prisma.OrderReferenceCounterWhereUniqueInput
}

/**
 * OrderReferenceCounter deleteMany
 */
export type OrderReferenceCounterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderReferenceCounters to delete
   */
  where?: Prisma.OrderReferenceCounterWhereInput
  /**
   * Limit how many OrderReferenceCounters to delete.
   */
  limit?: number
}

/**
 * OrderReferenceCounter without action
 */
export type OrderReferenceCounterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderReferenceCounter
   */
  select?: Prisma.OrderReferenceCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderReferenceCounter
   */
  omit?: Prisma.OrderReferenceCounterOmit<ExtArgs> | null
}
